"""
FoundationPose tracking using pre-generated Video Depth Anything depth maps.

Depth maps must be uint16 PNG files (mm) in test_scene_dir/depth/.
Generate them from the VDA NPZ output using:
    python3 -c "
    import numpy as np, cv2
    from pathlib import Path
    depths = np.load('...depths.npz')['depths']
    out = Path('.../depth'); out.mkdir(exist_ok=True)
    for i, d in enumerate(depths):
        cv2.imwrite(str(out/f'{i:06d}.png'), (d*1000).astype('uint16'))
    "
SAM2 video masks must be in test_scene_dir/masks/ (generated by run_sam2_video.py).
"""
import time
from estimater import *
from datareader import *
import argparse
from tools import *
import numpy as np

SAVE_VIDEO = False

# ── Occlusion re-init settings ─────────────────────────────────────────────────
# When the visible mask area drops below this fraction of the frame-0 area,
# the object is considered occluded. Lower = triggers sooner (hand just touching).
# Tune this first: 0.75 means 25% of the object must be hidden to trigger.
OCCLUSION_THRESHOLD = 0.75

# When occluded, re-run binary_search_depth every N frames to recover pose.
# Lower = more recoveries but slower. Set to 1 to re-init every occluded frame.
REINIT_EVERY_N = 5
# ──────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    code_dir = os.path.dirname(os.path.realpath(__file__))
    parser.add_argument("--mesh_file", type=str,
                        default=f"{code_dir}/demo_data/mustard0/mesh/textured_simple.obj")
    parser.add_argument("--test_scene_dir", type=str,
                        default=f"{code_dir}/demo_data/mustard0")
    parser.add_argument("--est_refine_iter", type=int, default=5)
    parser.add_argument("--track_refine_iter", type=int, default=1)
    parser.add_argument("--debug", type=int, default=1)
    parser.add_argument("--debug_dir", type=str, default=f"{code_dir}/debug")
    args = parser.parse_args()

    set_logging_format()
    set_seed(0)

    mesh = trimesh.load(args.mesh_file)
    mesh.apply_scale(0.001)

    debug = args.debug
    debug_dir = args.debug_dir
    os.system(f"rm -rf {debug_dir}/* && mkdir -p {debug_dir}/track_vis {debug_dir}/ob_in_cam")

    to_origin, extents = trimesh.bounds.oriented_bounds(mesh)
    bbox = np.stack([-extents / 2, extents / 2], axis=0).reshape(2, 3)

    scorer = ScorePredictor()
    refiner = PoseRefinePredictor()
    glctx = dr.RasterizeCudaContext()
    est = FoundationPose(
        model_pts=mesh.vertices,
        model_normals=mesh.vertex_normals,
        mesh=mesh,
        scorer=scorer,
        refiner=refiner,
        debug_dir=debug_dir,
        debug=debug,
        glctx=glctx,
    )
    logging.info("estimator initialization done")

    reader = YcbineoatReader(video_dir=args.test_scene_dir, shorter_side=None, zfar=np.inf)

    frame0_mask_area = None
    depth_scale = 1.0

    for i in range(len(reader.color_files)):
        color = reader.get_color(i)
        t1 = time.time()

        # load pre-generated VDA depth (uint16 mm -> float32 metres)
        depth_path = os.path.join(args.test_scene_dir, "depth", f"{reader.id_strs[i]}.png")
        depth = cv2.imread(depth_path, cv2.IMREAD_UNCHANGED).astype(np.float32) / 1000.0

        # load SAM2 video mask every frame
        mask_path = os.path.join(args.test_scene_dir, "masks", f"{reader.id_strs[i]}.png")
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)
        mask = (mask > 127).astype(np.uint8)

        if i == 0:
            # use binary_search_depth for robust mask-based initialization
            pose = binary_search_depth(est, mesh, color, mask.astype(bool), reader.K, debug=True)
            logging.info(f"Initial pose:\n{pose}")
            frame0_mask_area = float(mask.sum())
            # compute depth scale correction: align VDA depth to binary_search_depth z
            obj_pixels = mask > 0
            vda_z = depth[obj_pixels].mean() if obj_pixels.any() else 1.0
            bsd_z = float(pose[2, 3])
            depth_scale = bsd_z / vda_z if vda_z > 0 else 1.0
            logging.info(f"Depth scale correction: {depth_scale:.3f} (bsd_z={bsd_z:.3f}, vda_z={vda_z:.3f})")
        else:
            mask_area = float(mask.sum())
            occluded = (frame0_mask_area > 0) and (mask_area < OCCLUSION_THRESHOLD * frame0_mask_area)

            if occluded and (i % REINIT_EVERY_N == 0):
                logging.info(f"[frame {i}] Occlusion detected (area {mask_area:.0f} < {OCCLUSION_THRESHOLD}*{frame0_mask_area:.0f}), re-init with binary_search_depth")
                pose = binary_search_depth(est, mesh, color, mask.astype(bool), reader.K, debug=False)
            else:
                pose = est.track_one_new(
                    rgb=color, depth=depth * depth_scale, K=reader.K,
                    iteration=args.track_refine_iter, mask=mask
                )

        t2 = time.time()
        os.makedirs(f"{debug_dir}/ob_in_cam", exist_ok=True)
        np.savetxt(f"{debug_dir}/ob_in_cam/{reader.id_strs[i]}.txt", pose.reshape(4, 4))

        if debug >= 1:
            center_pose = pose @ np.linalg.inv(to_origin)
            color = cv2.putText(color, f"fps {int(1/(t2-t1))}", (10, 30),
                                cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 0, 0), 2)
            vis = draw_posed_3d_box(reader.K, img=color, ob_in_cam=center_pose, bbox=bbox)
            vis = draw_xyz_axis(color, ob_in_cam=center_pose, scale=0.1, K=reader.K,
                                thickness=3, transparency=0, is_input_rgb=True)

        if debug >= 2:
            os.makedirs(f"{debug_dir}/track_vis", exist_ok=True)
            imageio.imwrite(f"{debug_dir}/track_vis/{reader.id_strs[i]}.png", vis)
